export const CHANGE_COLOR_FILTER = 'CHANGE_COLOR_FILTER';
export const CHANGE_SIZE_FILTER = 'CHANGE_SIZE_FILTER';
export const CHANGE_BRAND_FILTER = 'CHANGE_BRAND_FILTER';
export const CHANGE_PRICE_FILTER = 'CHANGE_PRICE_FILTER';
export const RESET_FILTERS = 'RESET_FILTERS';
export const SET_ITEMS_FOUND = 'SET_ITEMS_FOUND';
export const SET_FILTER_OPEN = 'SET_FILTER_OPEN';
