export const SET_SHOPPING_CART_OPEN = 'SET_SHOPPING_CART_OPEN';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY';
