export const SET_SHOPPING_CART_OPEN = 'SET_SHOPPING_CART_OPEN';

export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';

export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const REMOVE_ALL_ITEMS = 'REMOVE_ALL_ITEMS';

export const CHANGE_QUANTITY = 'CHANGE_QUANTITY';

export const GET_COUNTRIES_REQUEST = 'GET_COUNTRIES_REQUEST';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';
export const GET_COUNTRIES_FAILURE = 'GET_COUNTRIES_FAILURE';

export const GET_CITIES_REQUEST = 'GET_CITIES_REQUEST';
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS';
export const GET_CITIES_FAILURE = 'GET_CITIES_FAILURE';

export const MAKE_ORDER_REQUEST = 'MAKE_ORDER_REQUEST';
export const MAKE_ORDER_SUCCESS = 'MAKE_ORDER_SUCCESS';
export const MAKE_ORDER_FAILURE = 'MAKE_ORDER_FAILURE';

export const CLEAR_ORDER_MESSAGE = 'CLEAR_ORDER_MESSAGE';
